# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (18)
# #########################################################################

class AttributeDefinition(BaseModel):
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    description: typing.Optional[str] = None

class AttributeValue(BaseModel):
    value: typing.Optional[str] = None
    type: typing.Optional[str] = None

class CharacterSpan(BaseModel):
    text: typing.Optional[str] = None
    start: typing.Optional[int] = None
    end: typing.Optional[int] = None

class Entity(BaseModel):
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    description: typing.Optional[str] = None
    custom_atts: typing.Dict[str, "AttributeValue"]

class EntityType(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    attributes: typing.List["AttributeDefinition"]

class EvidenceSpan(BaseModel):
    text: typing.Optional[str] = None
    start: typing.Optional[int] = None
    end: typing.Optional[int] = None

class ExtractionResult(BaseModel):
    triples: typing.List["Triple"]
    reasoning: typing.Optional[str] = None

class Ontology(BaseModel):
    entity_types: typing.List["EntityType"]
    relation_types: typing.List["RelationType"]

class OntologyExtension(BaseModel):
    needs_extension: typing.Optional[bool] = None
    new_entity_types: typing.List["EntityType"]
    new_relation_types: typing.List["RelationType"]
    critical_information_at_risk: typing.Optional[str] = None
    reasoning: typing.Optional[str] = None

class OntologyRecommendation(BaseModel):
    ontology: typing.Optional["Ontology"] = None
    text_purpose: typing.Optional[str] = None
    reasoning: typing.Optional[str] = None

class ProcessDependency(BaseModel):
    from_step: typing.Optional[str] = None
    to_step: typing.Optional[str] = None
    relation: typing.Optional[str] = None
    condition: typing.Optional[str] = None
    evidence: typing.List["EvidenceSpan"]

class ProcessExtractionIssue(BaseModel):
    code: typing.Optional[str] = None
    message: typing.Optional[str] = None
    related_step_ids: typing.List[str]

class ProcessExtractionResult(BaseModel):
    status: typing.Optional[typing.Union[str, str, str]] = None
    graph: typing.Optional["ProcessGraph"] = None
    reasoning: typing.Optional[str] = None
    issues: typing.List["ProcessExtractionIssue"]

class ProcessGraph(BaseModel):
    process_name: typing.Optional[str] = None
    scope: typing.Optional[str] = None
    primary_goal: typing.Optional[str] = None
    start_step_ids: typing.List[str]
    end_step_ids: typing.List[str]
    steps: typing.List["ProcessStep"]
    dependencies: typing.List["ProcessDependency"]
    notes: typing.List[str]

class ProcessStep(BaseModel):
    step_id: typing.Optional[str] = None
    title: typing.Optional[str] = None
    summary: typing.Optional[str] = None
    step_type: typing.Optional[types.ProcessStepType] = None
    actors: typing.List[str]
    inputs: typing.List[str]
    outputs: typing.List[str]
    duration: typing.Optional[str] = None
    prerequisites: typing.List[str]
    evidence: typing.List["EvidenceSpan"]

class RelationType(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    domain: typing.Optional[str] = None
    range: typing.Optional[str] = None

class SourceMetadata(BaseModel):
    source_name: typing.Optional[str] = None
    source_url: typing.Optional[str] = None

class Triple(BaseModel):
    subject: typing.Optional["Entity"] = None
    predicate: typing.Optional[str] = None
    object: typing.Optional["Entity"] = None
    source: typing.Optional["SourceMetadata"] = None
    supporting_spans: typing.List["CharacterSpan"]
    extraction_datetime: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
