# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (25)
# #########################################################################

class AttributeDefinition(BaseModel):
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    description: typing.Optional[str] = None

class AttributeValue(BaseModel):
    value: typing.Optional[str] = None
    type: typing.Optional[str] = None

class CharacterSpan(BaseModel):
    text: typing.Optional[str] = None
    start: typing.Optional[int] = None
    end: typing.Optional[int] = None

class EdgeForMatching(BaseModel):
    id: typing.Optional[str] = None
    subject: typing.Optional[str] = None
    predicate: typing.Optional[str] = None
    object: typing.Optional[str] = None
    evidence_summary: typing.Optional[str] = None

class EdgeMatch(BaseModel):
    edge1_id: typing.Optional[str] = None
    edge2_id: typing.Optional[str] = None
    is_duplicate: typing.Optional[bool] = None
    confidence_level: typing.Optional[str] = None
    reasoning: typing.Optional[str] = None

class EdgeMatchingResult(BaseModel):
    matches: typing.List["EdgeMatch"]
    reasoning: typing.Optional[str] = None

class Entity(BaseModel):
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    description: typing.Optional[str] = None
    custom_atts: typing.Dict[str, "AttributeValue"]

class EntityForMatching(BaseModel):
    id: typing.Optional[str] = None
    type: typing.Optional[str] = None
    description: typing.Optional[str] = None
    attributes: typing.Optional[str] = None

class EntityMatch(BaseModel):
    entity1_id: typing.Optional[str] = None
    entity2_id: typing.Optional[str] = None
    is_duplicate: typing.Optional[bool] = None
    confidence_level: typing.Optional[str] = None
    reasoning: typing.Optional[str] = None

class EntityMatchingResult(BaseModel):
    matches: typing.List["EntityMatch"]
    reasoning: typing.Optional[str] = None

class EntityType(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    attributes: typing.List["AttributeDefinition"]

class ExtractionResult(BaseModel):
    triples: typing.List["Triple"]
    reasoning: typing.Optional[str] = None

class MetadataElement(BaseModel):
    element_id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    element_type: typing.Optional[str] = None
    description: typing.Optional[str] = None
    data_type: typing.Optional[str] = None
    required: typing.Optional[bool] = None
    examples: typing.List[str]

class MetadataExtractionResult(BaseModel):
    elements: typing.List["MetadataElement"]
    reasoning: typing.Optional[str] = None

class Ontology(BaseModel):
    entity_types: typing.List["EntityType"]
    relation_types: typing.List["RelationType"]

class OntologyEnhancementResult(BaseModel):
    entity_types: typing.List["EntityType"]
    relation_types: typing.List["RelationType"]
    reasoning: typing.Optional[str] = None

class RelationType(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    domain: typing.Optional[str] = None
    range: typing.Optional[str] = None

class SourceMetadata(BaseModel):
    source_name: typing.Optional[str] = None
    source_url: typing.Optional[str] = None

class TaxonomyExtractionResult(BaseModel):
    relations: typing.List["TaxonomyRelation"]
    root_terms: typing.List[str]
    reasoning: typing.Optional[str] = None

class TaxonomyRelation(BaseModel):
    parent_term: typing.Optional[str] = None
    child_term: typing.Optional[str] = None
    relation_type: typing.Optional[str] = None
    confidence: typing.Optional[str] = None

class ThesaurusEntry(BaseModel):
    entry_id: typing.Optional[str] = None
    term_id: typing.Optional[str] = None
    preferred_label: typing.Optional[str] = None
    use_for: typing.List[str]
    broader_terms: typing.List[str]
    narrower_terms: typing.List[str]
    related_terms: typing.List[str]
    scope_note: typing.Optional[str] = None

class ThesaurusExtractionResult(BaseModel):
    entries: typing.List["ThesaurusEntry"]
    reasoning: typing.Optional[str] = None

class Triple(BaseModel):
    subject: typing.Optional["Entity"] = None
    predicate: typing.Optional[str] = None
    object: typing.Optional["Entity"] = None
    source: typing.Optional["SourceMetadata"] = None
    supporting_spans: typing.List["CharacterSpan"]
    extraction_datetime: typing.Optional[str] = None

class VocabularyExtractionResult(BaseModel):
    terms: typing.List["VocabularyTerm"]
    domain_summary: typing.Optional[str] = None
    reasoning: typing.Optional[str] = None

class VocabularyTerm(BaseModel):
    term_id: typing.Optional[str] = None
    preferred_label: typing.Optional[str] = None
    definition: typing.Optional[str] = None
    synonyms: typing.List[str]
    domain: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
