# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    def AnalyzeOntologyExtension(self, text: str,current_ontology: types.Ontology,scope: str,
        baml_options: BamlCallOptions = {},
    ) -> types.OntologyExtension:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.AnalyzeOntologyExtension(text=text,current_ontology=current_ontology,scope=scope,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="AnalyzeOntologyExtension", args={
                "text": text,"current_ontology": current_ontology,"scope": scope,
            })
            return typing.cast(types.OntologyExtension, result.cast_to(types, types, stream_types, False, __runtime__))
    def ConsolidateVocabulary(self, term_sets: typing.List[typing.List["types.VocabularyTerm"]],
        baml_options: BamlCallOptions = {},
    ) -> types.VocabularyExtractionResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ConsolidateVocabulary(term_sets=term_sets,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ConsolidateVocabulary", args={
                "term_sets": term_sets,
            })
            return typing.cast(types.VocabularyExtractionResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def EnhanceOntologyFromPipeline(self, text: str,vocabulary: typing.List["types.VocabularyTerm"],thesaurus_entries: typing.List["types.ThesaurusEntry"],scope: str,
        baml_options: BamlCallOptions = {},
    ) -> types.OntologyEnhancementResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.EnhanceOntologyFromPipeline(text=text,vocabulary=vocabulary,thesaurus_entries=thesaurus_entries,scope=scope,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="EnhanceOntologyFromPipeline", args={
                "text": text,"vocabulary": vocabulary,"thesaurus_entries": thesaurus_entries,"scope": scope,
            })
            return typing.cast(types.OntologyEnhancementResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractControlledVocabulary(self, text: str,existing_terms: typing.List["types.VocabularyTerm"],document_id: str,
        baml_options: BamlCallOptions = {},
    ) -> types.VocabularyExtractionResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractControlledVocabulary(text=text,existing_terms=existing_terms,document_id=document_id,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractControlledVocabulary", args={
                "text": text,"existing_terms": existing_terms,"document_id": document_id,
            })
            return typing.cast(types.VocabularyExtractionResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractMetadataSchema(self, text: str,document_metadata: str,existing_elements: typing.List["types.MetadataElement"],
        baml_options: BamlCallOptions = {},
    ) -> types.MetadataExtractionResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractMetadataSchema(text=text,document_metadata=document_metadata,existing_elements=existing_elements,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractMetadataSchema", args={
                "text": text,"document_metadata": document_metadata,"existing_elements": existing_elements,
            })
            return typing.cast(types.MetadataExtractionResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractProcessGraph(self, text: str,process_hint: typing.Optional[str] = None,existing_graph: typing.Optional["types.ProcessGraph"] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.ProcessExtractionResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractProcessGraph(text=text,process_hint=process_hint,existing_graph=existing_graph,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractProcessGraph", args={
                "text": text,"process_hint": process_hint,"existing_graph": existing_graph,
            })
            return typing.cast(types.ProcessExtractionResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractTaxonomy(self, terms: typing.List["types.VocabularyTerm"],text: str,existing_relations: typing.List["types.TaxonomyRelation"],
        baml_options: BamlCallOptions = {},
    ) -> types.TaxonomyExtractionResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractTaxonomy(terms=terms,text=text,existing_relations=existing_relations,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractTaxonomy", args={
                "terms": terms,"text": text,"existing_relations": existing_relations,
            })
            return typing.cast(types.TaxonomyExtractionResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractThesaurus(self, terms: typing.List["types.VocabularyTerm"],taxonomy_relations: typing.List["types.TaxonomyRelation"],text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ThesaurusExtractionResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractThesaurus(terms=terms,taxonomy_relations=taxonomy_relations,text=text,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractThesaurus", args={
                "terms": terms,"taxonomy_relations": taxonomy_relations,"text": text,
            })
            return typing.cast(types.ThesaurusExtractionResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractTriples(self, text: str,ontology: types.Ontology,source_metadata: types.SourceMetadata,existing_triples: typing.List["types.Triple"],
        baml_options: BamlCallOptions = {},
    ) -> types.ExtractionResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractTriples(text=text,ontology=ontology,source_metadata=source_metadata,existing_triples=existing_triples,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractTriples", args={
                "text": text,"ontology": ontology,"source_metadata": source_metadata,"existing_triples": existing_triples,
            })
            return typing.cast(types.ExtractionResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def MatchEdges(self, edges: typing.List["types.EdgeForMatching"],context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.EdgeMatchingResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.MatchEdges(edges=edges,context=context,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="MatchEdges", args={
                "edges": edges,"context": context,
            })
            return typing.cast(types.EdgeMatchingResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def MatchEntities(self, entities: typing.List["types.EntityForMatching"],context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.EntityMatchingResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.MatchEntities(entities=entities,context=context,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="MatchEntities", args={
                "entities": entities,"context": context,
            })
            return typing.cast(types.EntityMatchingResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def RecommendOntology(self, text: str,scope: str,
        baml_options: BamlCallOptions = {},
    ) -> types.OntologyRecommendation:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.RecommendOntology(text=text,scope=scope,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="RecommendOntology", args={
                "text": text,"scope": scope,
            })
            return typing.cast(types.OntologyRecommendation, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeOntologyExtension(self, text: str,current_ontology: types.Ontology,scope: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.OntologyExtension, types.OntologyExtension]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="AnalyzeOntologyExtension", args={
            "text": text,"current_ontology": current_ontology,"scope": scope,
        })
        return baml_py.BamlSyncStream[stream_types.OntologyExtension, types.OntologyExtension](
          result,
          lambda x: typing.cast(stream_types.OntologyExtension, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.OntologyExtension, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ConsolidateVocabulary(self, term_sets: typing.List[typing.List["types.VocabularyTerm"]],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.VocabularyExtractionResult, types.VocabularyExtractionResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ConsolidateVocabulary", args={
            "term_sets": term_sets,
        })
        return baml_py.BamlSyncStream[stream_types.VocabularyExtractionResult, types.VocabularyExtractionResult](
          result,
          lambda x: typing.cast(stream_types.VocabularyExtractionResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.VocabularyExtractionResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def EnhanceOntologyFromPipeline(self, text: str,vocabulary: typing.List["types.VocabularyTerm"],thesaurus_entries: typing.List["types.ThesaurusEntry"],scope: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.OntologyEnhancementResult, types.OntologyEnhancementResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="EnhanceOntologyFromPipeline", args={
            "text": text,"vocabulary": vocabulary,"thesaurus_entries": thesaurus_entries,"scope": scope,
        })
        return baml_py.BamlSyncStream[stream_types.OntologyEnhancementResult, types.OntologyEnhancementResult](
          result,
          lambda x: typing.cast(stream_types.OntologyEnhancementResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.OntologyEnhancementResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractControlledVocabulary(self, text: str,existing_terms: typing.List["types.VocabularyTerm"],document_id: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.VocabularyExtractionResult, types.VocabularyExtractionResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractControlledVocabulary", args={
            "text": text,"existing_terms": existing_terms,"document_id": document_id,
        })
        return baml_py.BamlSyncStream[stream_types.VocabularyExtractionResult, types.VocabularyExtractionResult](
          result,
          lambda x: typing.cast(stream_types.VocabularyExtractionResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.VocabularyExtractionResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractMetadataSchema(self, text: str,document_metadata: str,existing_elements: typing.List["types.MetadataElement"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.MetadataExtractionResult, types.MetadataExtractionResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractMetadataSchema", args={
            "text": text,"document_metadata": document_metadata,"existing_elements": existing_elements,
        })
        return baml_py.BamlSyncStream[stream_types.MetadataExtractionResult, types.MetadataExtractionResult](
          result,
          lambda x: typing.cast(stream_types.MetadataExtractionResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.MetadataExtractionResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractProcessGraph(self, text: str,process_hint: typing.Optional[str] = None,existing_graph: typing.Optional["types.ProcessGraph"] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ProcessExtractionResult, types.ProcessExtractionResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractProcessGraph", args={
            "text": text,"process_hint": process_hint,"existing_graph": existing_graph,
        })
        return baml_py.BamlSyncStream[stream_types.ProcessExtractionResult, types.ProcessExtractionResult](
          result,
          lambda x: typing.cast(stream_types.ProcessExtractionResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ProcessExtractionResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractTaxonomy(self, terms: typing.List["types.VocabularyTerm"],text: str,existing_relations: typing.List["types.TaxonomyRelation"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.TaxonomyExtractionResult, types.TaxonomyExtractionResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractTaxonomy", args={
            "terms": terms,"text": text,"existing_relations": existing_relations,
        })
        return baml_py.BamlSyncStream[stream_types.TaxonomyExtractionResult, types.TaxonomyExtractionResult](
          result,
          lambda x: typing.cast(stream_types.TaxonomyExtractionResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.TaxonomyExtractionResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractThesaurus(self, terms: typing.List["types.VocabularyTerm"],taxonomy_relations: typing.List["types.TaxonomyRelation"],text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ThesaurusExtractionResult, types.ThesaurusExtractionResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractThesaurus", args={
            "terms": terms,"taxonomy_relations": taxonomy_relations,"text": text,
        })
        return baml_py.BamlSyncStream[stream_types.ThesaurusExtractionResult, types.ThesaurusExtractionResult](
          result,
          lambda x: typing.cast(stream_types.ThesaurusExtractionResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ThesaurusExtractionResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractTriples(self, text: str,ontology: types.Ontology,source_metadata: types.SourceMetadata,existing_triples: typing.List["types.Triple"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ExtractionResult, types.ExtractionResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractTriples", args={
            "text": text,"ontology": ontology,"source_metadata": source_metadata,"existing_triples": existing_triples,
        })
        return baml_py.BamlSyncStream[stream_types.ExtractionResult, types.ExtractionResult](
          result,
          lambda x: typing.cast(stream_types.ExtractionResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ExtractionResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def MatchEdges(self, edges: typing.List["types.EdgeForMatching"],context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.EdgeMatchingResult, types.EdgeMatchingResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="MatchEdges", args={
            "edges": edges,"context": context,
        })
        return baml_py.BamlSyncStream[stream_types.EdgeMatchingResult, types.EdgeMatchingResult](
          result,
          lambda x: typing.cast(stream_types.EdgeMatchingResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.EdgeMatchingResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def MatchEntities(self, entities: typing.List["types.EntityForMatching"],context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.EntityMatchingResult, types.EntityMatchingResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="MatchEntities", args={
            "entities": entities,"context": context,
        })
        return baml_py.BamlSyncStream[stream_types.EntityMatchingResult, types.EntityMatchingResult](
          result,
          lambda x: typing.cast(stream_types.EntityMatchingResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.EntityMatchingResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def RecommendOntology(self, text: str,scope: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.OntologyRecommendation, types.OntologyRecommendation]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="RecommendOntology", args={
            "text": text,"scope": scope,
        })
        return baml_py.BamlSyncStream[stream_types.OntologyRecommendation, types.OntologyRecommendation](
          result,
          lambda x: typing.cast(stream_types.OntologyRecommendation, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.OntologyRecommendation, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeOntologyExtension(self, text: str,current_ontology: types.Ontology,scope: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzeOntologyExtension", args={
            "text": text,"current_ontology": current_ontology,"scope": scope,
        }, mode="request")
        return result
    def ConsolidateVocabulary(self, term_sets: typing.List[typing.List["types.VocabularyTerm"]],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ConsolidateVocabulary", args={
            "term_sets": term_sets,
        }, mode="request")
        return result
    def EnhanceOntologyFromPipeline(self, text: str,vocabulary: typing.List["types.VocabularyTerm"],thesaurus_entries: typing.List["types.ThesaurusEntry"],scope: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="EnhanceOntologyFromPipeline", args={
            "text": text,"vocabulary": vocabulary,"thesaurus_entries": thesaurus_entries,"scope": scope,
        }, mode="request")
        return result
    def ExtractControlledVocabulary(self, text: str,existing_terms: typing.List["types.VocabularyTerm"],document_id: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractControlledVocabulary", args={
            "text": text,"existing_terms": existing_terms,"document_id": document_id,
        }, mode="request")
        return result
    def ExtractMetadataSchema(self, text: str,document_metadata: str,existing_elements: typing.List["types.MetadataElement"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractMetadataSchema", args={
            "text": text,"document_metadata": document_metadata,"existing_elements": existing_elements,
        }, mode="request")
        return result
    def ExtractProcessGraph(self, text: str,process_hint: typing.Optional[str] = None,existing_graph: typing.Optional["types.ProcessGraph"] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractProcessGraph", args={
            "text": text,"process_hint": process_hint,"existing_graph": existing_graph,
        }, mode="request")
        return result
    def ExtractTaxonomy(self, terms: typing.List["types.VocabularyTerm"],text: str,existing_relations: typing.List["types.TaxonomyRelation"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractTaxonomy", args={
            "terms": terms,"text": text,"existing_relations": existing_relations,
        }, mode="request")
        return result
    def ExtractThesaurus(self, terms: typing.List["types.VocabularyTerm"],taxonomy_relations: typing.List["types.TaxonomyRelation"],text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractThesaurus", args={
            "terms": terms,"taxonomy_relations": taxonomy_relations,"text": text,
        }, mode="request")
        return result
    def ExtractTriples(self, text: str,ontology: types.Ontology,source_metadata: types.SourceMetadata,existing_triples: typing.List["types.Triple"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractTriples", args={
            "text": text,"ontology": ontology,"source_metadata": source_metadata,"existing_triples": existing_triples,
        }, mode="request")
        return result
    def MatchEdges(self, edges: typing.List["types.EdgeForMatching"],context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="MatchEdges", args={
            "edges": edges,"context": context,
        }, mode="request")
        return result
    def MatchEntities(self, entities: typing.List["types.EntityForMatching"],context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="MatchEntities", args={
            "entities": entities,"context": context,
        }, mode="request")
        return result
    def RecommendOntology(self, text: str,scope: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RecommendOntology", args={
            "text": text,"scope": scope,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeOntologyExtension(self, text: str,current_ontology: types.Ontology,scope: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzeOntologyExtension", args={
            "text": text,"current_ontology": current_ontology,"scope": scope,
        }, mode="stream")
        return result
    def ConsolidateVocabulary(self, term_sets: typing.List[typing.List["types.VocabularyTerm"]],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ConsolidateVocabulary", args={
            "term_sets": term_sets,
        }, mode="stream")
        return result
    def EnhanceOntologyFromPipeline(self, text: str,vocabulary: typing.List["types.VocabularyTerm"],thesaurus_entries: typing.List["types.ThesaurusEntry"],scope: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="EnhanceOntologyFromPipeline", args={
            "text": text,"vocabulary": vocabulary,"thesaurus_entries": thesaurus_entries,"scope": scope,
        }, mode="stream")
        return result
    def ExtractControlledVocabulary(self, text: str,existing_terms: typing.List["types.VocabularyTerm"],document_id: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractControlledVocabulary", args={
            "text": text,"existing_terms": existing_terms,"document_id": document_id,
        }, mode="stream")
        return result
    def ExtractMetadataSchema(self, text: str,document_metadata: str,existing_elements: typing.List["types.MetadataElement"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractMetadataSchema", args={
            "text": text,"document_metadata": document_metadata,"existing_elements": existing_elements,
        }, mode="stream")
        return result
    def ExtractProcessGraph(self, text: str,process_hint: typing.Optional[str] = None,existing_graph: typing.Optional["types.ProcessGraph"] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractProcessGraph", args={
            "text": text,"process_hint": process_hint,"existing_graph": existing_graph,
        }, mode="stream")
        return result
    def ExtractTaxonomy(self, terms: typing.List["types.VocabularyTerm"],text: str,existing_relations: typing.List["types.TaxonomyRelation"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractTaxonomy", args={
            "terms": terms,"text": text,"existing_relations": existing_relations,
        }, mode="stream")
        return result
    def ExtractThesaurus(self, terms: typing.List["types.VocabularyTerm"],taxonomy_relations: typing.List["types.TaxonomyRelation"],text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractThesaurus", args={
            "terms": terms,"taxonomy_relations": taxonomy_relations,"text": text,
        }, mode="stream")
        return result
    def ExtractTriples(self, text: str,ontology: types.Ontology,source_metadata: types.SourceMetadata,existing_triples: typing.List["types.Triple"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractTriples", args={
            "text": text,"ontology": ontology,"source_metadata": source_metadata,"existing_triples": existing_triples,
        }, mode="stream")
        return result
    def MatchEdges(self, edges: typing.List["types.EdgeForMatching"],context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="MatchEdges", args={
            "edges": edges,"context": context,
        }, mode="stream")
        return result
    def MatchEntities(self, entities: typing.List["types.EntityForMatching"],context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="MatchEntities", args={
            "entities": entities,"context": context,
        }, mode="stream")
        return result
    def RecommendOntology(self, text: str,scope: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RecommendOntology", args={
            "text": text,"scope": scope,
        }, mode="stream")
        return result
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))