# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AttributeDefinition": types.AttributeDefinition,
    "stream_types.AttributeDefinition": stream_types.AttributeDefinition,

    "types.AttributeValue": types.AttributeValue,
    "stream_types.AttributeValue": stream_types.AttributeValue,

    "types.CharacterSpan": types.CharacterSpan,
    "stream_types.CharacterSpan": stream_types.CharacterSpan,

    "types.EdgeForMatching": types.EdgeForMatching,
    "stream_types.EdgeForMatching": stream_types.EdgeForMatching,

    "types.EdgeMatch": types.EdgeMatch,
    "stream_types.EdgeMatch": stream_types.EdgeMatch,

    "types.EdgeMatchingResult": types.EdgeMatchingResult,
    "stream_types.EdgeMatchingResult": stream_types.EdgeMatchingResult,

    "types.Entity": types.Entity,
    "stream_types.Entity": stream_types.Entity,

    "types.EntityForMatching": types.EntityForMatching,
    "stream_types.EntityForMatching": stream_types.EntityForMatching,

    "types.EntityMatch": types.EntityMatch,
    "stream_types.EntityMatch": stream_types.EntityMatch,

    "types.EntityMatchingResult": types.EntityMatchingResult,
    "stream_types.EntityMatchingResult": stream_types.EntityMatchingResult,

    "types.EntityType": types.EntityType,
    "stream_types.EntityType": stream_types.EntityType,

    "types.EvidenceSpan": types.EvidenceSpan,
    "stream_types.EvidenceSpan": stream_types.EvidenceSpan,

    "types.ExtractionResult": types.ExtractionResult,
    "stream_types.ExtractionResult": stream_types.ExtractionResult,

    "types.MetadataElement": types.MetadataElement,
    "stream_types.MetadataElement": stream_types.MetadataElement,

    "types.MetadataExtractionResult": types.MetadataExtractionResult,
    "stream_types.MetadataExtractionResult": stream_types.MetadataExtractionResult,

    "types.Ontology": types.Ontology,
    "stream_types.Ontology": stream_types.Ontology,

    "types.OntologyEnhancementResult": types.OntologyEnhancementResult,
    "stream_types.OntologyEnhancementResult": stream_types.OntologyEnhancementResult,

    "types.OntologyExtension": types.OntologyExtension,
    "stream_types.OntologyExtension": stream_types.OntologyExtension,

    "types.OntologyRecommendation": types.OntologyRecommendation,
    "stream_types.OntologyRecommendation": stream_types.OntologyRecommendation,

    "types.ProcessDependency": types.ProcessDependency,
    "stream_types.ProcessDependency": stream_types.ProcessDependency,

    "types.ProcessExtractionIssue": types.ProcessExtractionIssue,
    "stream_types.ProcessExtractionIssue": stream_types.ProcessExtractionIssue,

    "types.ProcessExtractionResult": types.ProcessExtractionResult,
    "stream_types.ProcessExtractionResult": stream_types.ProcessExtractionResult,

    "types.ProcessGraph": types.ProcessGraph,
    "stream_types.ProcessGraph": stream_types.ProcessGraph,

    "types.ProcessStep": types.ProcessStep,
    "stream_types.ProcessStep": stream_types.ProcessStep,

    "types.RelationType": types.RelationType,
    "stream_types.RelationType": stream_types.RelationType,

    "types.SourceMetadata": types.SourceMetadata,
    "stream_types.SourceMetadata": stream_types.SourceMetadata,

    "types.TaxonomyExtractionResult": types.TaxonomyExtractionResult,
    "stream_types.TaxonomyExtractionResult": stream_types.TaxonomyExtractionResult,

    "types.TaxonomyRelation": types.TaxonomyRelation,
    "stream_types.TaxonomyRelation": stream_types.TaxonomyRelation,

    "types.ThesaurusEntry": types.ThesaurusEntry,
    "stream_types.ThesaurusEntry": stream_types.ThesaurusEntry,

    "types.ThesaurusExtractionResult": types.ThesaurusExtractionResult,
    "stream_types.ThesaurusExtractionResult": stream_types.ThesaurusExtractionResult,

    "types.Triple": types.Triple,
    "stream_types.Triple": stream_types.Triple,

    "types.VocabularyExtractionResult": types.VocabularyExtractionResult,
    "stream_types.VocabularyExtractionResult": stream_types.VocabularyExtractionResult,

    "types.VocabularyTerm": types.VocabularyTerm,
    "stream_types.VocabularyTerm": stream_types.VocabularyTerm,


    "types.ProcessStepType": types.ProcessStepType,

}