# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeOntologyExtension(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.OntologyExtension:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeOntologyExtension", llm_response=llm_response, mode="request")
        return typing.cast(types.OntologyExtension, result)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="request")
        return typing.cast(types.Resume, result)

    def ExtractTriples(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ExtractionResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractTriples", llm_response=llm_response, mode="request")
        return typing.cast(types.ExtractionResult, result)

    def RecommendOntology(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.OntologyRecommendation:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RecommendOntology", llm_response=llm_response, mode="request")
        return typing.cast(types.OntologyRecommendation, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeOntologyExtension(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.OntologyExtension:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeOntologyExtension", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.OntologyExtension, result)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Resume, result)

    def ExtractTriples(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ExtractionResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractTriples", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ExtractionResult, result)

    def RecommendOntology(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.OntologyRecommendation:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RecommendOntology", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.OntologyRecommendation, result)

    