# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CharacterSpan": types.CharacterSpan,
    "stream_types.CharacterSpan": stream_types.CharacterSpan,

    "types.EntityType": types.EntityType,
    "stream_types.EntityType": stream_types.EntityType,

    "types.ExtractionResult": types.ExtractionResult,
    "stream_types.ExtractionResult": stream_types.ExtractionResult,

    "types.Ontology": types.Ontology,
    "stream_types.Ontology": stream_types.Ontology,

    "types.OntologyExtension": types.OntologyExtension,
    "stream_types.OntologyExtension": stream_types.OntologyExtension,

    "types.OntologyRecommendation": types.OntologyRecommendation,
    "stream_types.OntologyRecommendation": stream_types.OntologyRecommendation,

    "types.RelationType": types.RelationType,
    "stream_types.RelationType": stream_types.RelationType,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.SourceMetadata": types.SourceMetadata,
    "stream_types.SourceMetadata": stream_types.SourceMetadata,

    "types.Triple": types.Triple,
    "stream_types.Triple": stream_types.Triple,


}